### ISSUE TITLE
AYS service daemon

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/ays9#105]
# What
One or more long running actions that can be optionally configured per service.

# Why
We need this to monitor logging from zero-os nodes. Basically the zero-os logging will spit out a standardized log format via a pub/sub mechanism from which events can then be propagated to the designated AYS service via calling a standardized method on it.

# When should the daemon be running
Anytime the service has status running, as long as it did not stop itself. If an exception is raised, AYS should restart it if the service is still "running".

# How
The action should be implemented as an async method, not using a designated thread.

# How to stop the daemon 
```python
async def my_daemon():
    # stop daemon
    return True
```

**Comment by rkhamis** [comment]
I think the correct approach is to avoid running in the server's main thread. We expose APIs that allow people to create their own actor templates or update existing ones.
This allows for anyone to intentionally or unintentionally block the main process.

Instead, I believe this should be implemented using the job, by firing up a coroutine. They're inexpensive and are a lot less harmful to the health of the server. However, we need to consider scalability.
The other approach is to run all "long running" jobs in a different thread than the main server. So if one blocks, at least it blocks only the other long running jobs.

**Comment by xmonader** [comment]
I'm not in favor of this, correct me if I'm wrong. Having this feature will introduce bugs into AYS. at least code written in a wrong way can just block ays main execution, and we don't have control on the service actions code by any means.

**Comment by zaibon** [comment]
So here is the current situation.
AYS runs on top of an event loop. Since we can't predict what code is going to be run in the jobs, we execute each job in its own thread, so we are sure to never block the event loop.

Now, with this new long running job that we need, we can't use the current implementation cause that won't scale. We could end up with 1000+ threads, that not going to work.

So the idea was to use a real coroutine to run the long runnning job. But, in this case, only asynchronous code can be used, cause other wise any blocking call would block the event loop.

I agree that this is dangerous since we rely on user doing the right thing. So it's all about documenting this properly.
On the other hand I don't have any other idea for now how we could do it.

**Comment by rkhamis** [comment]
We're currently investigating an approach that combines greenlets in a sanic task.

**Comment by xmonader** [comment]
We have initial working FR: https://github.com/Jumpscale/ays9/pull/112 

Problem: 
* When having a blocked AYS server due to blocking code in the coroutine we need a way to recover. restarting AYS will start ays in blocked state.

Suggestion: start the long running jobs in a thread `when --dev is passed to ays` instead of deleting the service.
