### ISSUE TITLE
ays actor update not loading latest code

### ISSUE THREAD

**Issue by jvwilder** [Jumpscale/ays9#127]
#### Installation information

- jumpscale version: master
- operating system: Ubuntu 16.04

#### Detailed description
Sometimes 'ays actor update' isn't loading the latest template code. Ays then just keeps using the old code. Running ays actor update, restarting the ays service or removing the temporary files of the template doesn't solve the problem.

#### Steps to reproduce
So when template code is giving an error during execution, the changes that fix the error are not loaded by ays and it just keeps executing the old code that crashed with the error.

**Comment by ahussein** [comment]
I was not able to reproduce this problem using an installation of jumpscale from master branch on an ubuntu 16.04 system.
Steps:

- Create new actor template and implement the install action as follow
`

def install(job):
    """
    Install action
    """
    raise RuntimeError('hello')
    pass

`
- Create a service of the actor in a bp and execute the bp
- Create  a run and execute it ..> Run state is Error and the error is seen in the logs
- Fix the code by commenting out the raise statement
- Execute ays actor update command
- The run status changes to ok since the error job will be rescheduled and will be executed successfully

**Comment by jvwilder** [comment]
I got this a couple of times and each time after an error in the container template. I am also not able to reproduce it at the moment.

**Comment by ahussein** [comment]
okay. Can you please re-open this ticket when you are able to reproduce.
