### ISSUE TITLE
Cover new IO limitation options of vdisks in OVC 2.1.7

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/ays9#187]
Finegrained IO limitation options have been added on the OVC api v2.1.7.

These need to be reflected in the OVC templates.

part of #64

**Comment by alichaddad** [comment]
Needs environment with enough resources to test the implemetation

**Comment by john-kheir** [comment]
https://github.com/Jumpscale/ays9/blob/3606007bd5cbd8b86140a02ace68ecb8b4f32a06/templates/disk/disk.ovc/README.md

@alichaddad  Can you please give an explanation to the parameters given in this schema and how they are related to each other?

**Comment by rkhamis** [comment]
Like I said, libvirt's limits. See http://libvirt.org/formatdomain.html#elementsDisks

**Comment by ramezsaeed** [comment]
@rkhamis 
Please we need at least one example in the docs of how to use the params;
we only need to verify, it will be wasting time to go and understand libvirt for now

**Comment by rkhamis** [comment]
@ramezsaeed we expose the API that OVC implements. I don't have the know how either. When I tried digging in the code, I came across this libvirt's elements. this is from the above link's documentation

> total_bytes_sec
The optional total_bytes_sec element is the total throughput limit in bytes per second. This cannot appear with read_bytes_sec or write_bytes_sec.
read_bytes_sec
The optional read_bytes_sec element is the read throughput limit in bytes per second.
write_bytes_sec
The optional write_bytes_sec element is the write throughput limit in bytes per second.
total_iops_sec
The optional total_iops_sec element is the total I/O operations per second. This cannot appear with read_iops_sec or write_iops_sec.
read_iops_sec
The optional read_iops_sec element is the read I/O operations per second.
write_iops_sec
The optional write_iops_sec element is the write I/O operations per second.
total_bytes_sec_max
The optional total_bytes_sec_max element is the maximum total throughput limit in bytes per second. This cannot appear with read_bytes_sec_max or write_bytes_sec_max.
read_bytes_sec_max
The optional read_bytes_sec_max element is the maximum read throughput limit in bytes per second.
write_bytes_sec_max
The optional write_bytes_sec_max element is the maximum write throughput limit in bytes per second.
total_iops_sec_max
The optional total_iops_sec_max element is the maximum total I/O operations per second. This cannot appear with read_iops_sec_max or write_iops_sec_max.
read_iops_sec_max
The optional read_iops_sec_max element is the maximum read I/O operations per second.
write_iops_sec_max
The optional write_iops_sec_max element is the maximum write I/O operations per second.
size_iops_sec
The optional size_iops_sec element is the size of I/O operations per second.
Throughput limits since 1.2.11 and QEMU 1.7

**Comment by john-kheir** [comment]
#### Detailed description
When these params readIopsSecMax: 200, writeIopsSecMax: 100 are provided, 
1- ays throw the given stack trace
2- maxIOPS are not working any more and not limited to 600 (however if i just provided the maxIOPS without any other parameters, it will work fine)
```
Disk stats (read/write):
  vdb: ios=100708/25300, merge=0/0, ticks=414884/186196, in_queue=601360, util=98.52%

``` 
```
g8client__env:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: '****'
    password: '****'
    account: 'john666'

vdc__vdc2:
    description: 'vdc for demo'
    g8client: 'env'
    account: 'john666'
    location: 'du-conv-2'

disk.ovc__disk1:
   size: 5
   g8client: 'env'
   description: 'data disk'
   type: 'D'
   maxIOPS: 600
   readIopsSecMax: 200
   writeIopsSecMax: 100
   location: 'du-conv-2'

# create the vm.
# expose ports 22. Map it to 2210.
node.ovc__demo1:
    bootdisk.size: 50
    memory: 2
    os.image: 'Ubuntu 16.04 x64'
    ports:
        - '2210:22'
    disk:
      - 'disk1'

actions:

```


#### Steps to reproduce



#### Relevant stacktraces
```
2017-09-24 14:40:37 - (network)[INFO][127.0.0.1:46916]: GET http://localhost:5000/ays/repository/test3/aysrun/011b2bf362fccf7351b66657698a4354  200 1973
[Sun24 14:40] - Job.py              :56  :j.core.jobcontroller.job.03eb8de89dced5950a86d76456e1214d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/d5bddc9a06de0e0ff521350f63ce3da3.py", line 365, in install
    raise e
  File "/tmp/actions/node.ovc/d5bddc9a06de0e0ff521350f63ce3da3.py", line 356, in install
    _configure_disks(service, machine, prefab)
  File "/tmp/actions/node.ovc/d5bddc9a06de0e0ff521350f63ce3da3.py", line 455, in _configure_disks
    disk_args.sizeIopsSec, disk_args.maxIOPS)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 634, in disk_limit_io
    size_iops_sec=size_iops_sec)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 500 Internal Server Error
b'Your service request could not be fulfilled correctly, please contact support and mention "eco-777-cb8323ff-0016-2e25-758b-a0685cd1c08b".'
[Sun24 14:40] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 4: error
[Sun24 14:40] - Run.py              :118 :j.atyourservice.server         - ERROR    - error during execution of step 4 in run 011b2bf362fccf7351b66657698a4354
Error of job: node.ovc!demo1 (install):
*TRACEBACK*********************************************************************************
JumpScale9Lib.clients.portal.PortalClient.ApiError: 500 Internal Server Error
b'Your service request could not be fulfilled correctly, please contact support and mention "eco-777-cb8323ff-0016-2e25-758b-a0685cd1c08b".'


******************************************************************************************

```
## Note 
the rest of the parameters are not tried yet
## Request 
@rkhamis @alichaddad  Please add the docs Reem already provided to our docs here --> https://github.com/Jumpscale/ays9/blob/3606007bd5cbd8b86140a02ace68ecb8b4f32a06/templates/disk/disk.ovc/README.md

**Comment by john-kheir** [comment]
@alichaddad What is the difference between totalIopsSecMax and maxIOPS? .. as for me they look the same.

**Comment by rkhamis** [comment]
@john-kheir if I had to guess, I'd say totalIopsSecMax is the maximum limitation in a sec while maxIOPS would probably take a more average look, meaning it would compensate for spikes. Just a guess.
