### ISSUE TITLE
username/passwords --- feature request

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/ays9#210]
Guys,

Any chance of not including credentials at all in the blueprints?
Based on experience from previous cloud providers, whenever credentials are allowed within templates the chances of publishing those on-line and/or making mistakes is extremely high.

Would be possible to make a plan around the security of these details, please?

**Note: I have noticed there is now a validity flag in IYO. From the top of my head if using a blueprint that would be requesting a new ok every-time a transaction happens so we take into consideration the validity should be for just the session or a very short time***

Adding @yveskerwyn 

Thanks

**Comment by yveskerwyn** [comment]
Thanks Gonzalo, I switched to using JWT instead of username/password in the example blueprints, but we indeed still have some old documentation with credentials (mea culpa!)...  I removed them from the update documentation branch (still needs to be merged), I also made sure of course that the these old credentials don't work anymore

Fully agree on enforcing usage of the validity flag, we should not accept JWTs that don't expire.

@grimpy something to discuss for OVC too...

**Comment by yveskerwyn** [comment]
the config manager will solve this, will be part of 9.3.0 templates
